### ISSUE TITLE
[Enhancement suggestion]: Example data/vignette of the input files needed

### ISSUE THREAD

**Issue by SziKayLeung** [ejh243/BrainFANS#20]
### Enhancement suggestion

Hi, 

It's my first time trying to run the neural neuralCellComposition analysis (DNAm/analysis/neuralCellComposition) and have noticed a series of Rscripts that require different arguments i.e. path to folder with array annotation files - what should these annotation files look like? i.e path to csv file with reference panels specified - is there a specific format for the csv file? 

Also looking into the fitModelsAll.r, and apologies if I'm missing something, but there seem to be some pre-requisite input files needed:  
```
crosshyb<-read.csv(file.path(refPath, "CrossHybridisingProbesPriceORWeksberg.csv"), row.names = 1)
probes<-read.csv(file.path(refPath, "SNPsinProbesAnno.csv"), row.names = 1)
``` 

Should there be a config file where I load in my own input files? 
Thank you!

**Comment by sof202** [comment]
I don't know much about neural cell decomposition, but this might be useful?

An example of these .csv files can be found in `/lustre/projects/Research_Project-MRC190311/references/450K_reference`.
You might be able to get some more information after looking the the two files

**Comment by eld211** [comment]
Dear Szi Kay, you need a config file that will have the file paths to the relevant files, there should be some examples in the scripts folder

**Comment by ejh243** [comment]
Hi Szi Kay,

These analysis scripts were not designed to be run with a config file partly because they were going to call on data from different projects that predated this standardized way of working. 

A list of the arguments needed for those scripts can be found in the [README ](https://github.com/ejh243/BrainFANS/blob/master/array/DNAm/analysis/neuralCellComposition/README.md). I appreciate though that doesn't answer your question for what they should look like. 

Agree that we should have some data for the purpose of testing and developing scripts. For DNAm we discussed have a folder called `devData` on ISCA which we could use for this purpose. I recommend that we create a similar folder for each modality. For the time being I would not commit this data to the pipeline.
